# Generated by Django 6.0.4 on 2026-04-12 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Énoncé de la question')),
                ('question_type', models.CharField(choices=[('qcm', 'QCM (choix multiples)'), ('vrai_faux', 'Vrai / Faux')], default='qcm', max_length=10, verbose_name='Type de question')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Points')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Texte de la réponse')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Réponse correcte')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du quiz')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Pourcentage minimum pour valider le quiz (ex: 70 = 70%)', verbose_name='Score de validation (%)')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quizzes',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score (%)')),
                ('earned_points', models.PositiveIntegerField(default=0, verbose_name='Points obtenus')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Total points possibles')),
                ('passed', models.BooleanField(default=False, verbose_name='Quiz validé')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de tentative')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant')),
            ],
            options={
                'verbose_name': 'Tentative de quiz',
                'verbose_name_plural': 'Tentatives de quiz',
                'db_table': 'quiz_attempts',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Réponse correcte')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.answer', verbose_name='Réponse choisie')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question', verbose_name='Question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='quizzes.quizattempt', verbose_name='Tentative')),
            ],
            options={
                'verbose_name': 'Réponse de tentative',
                'verbose_name_plural': 'Réponses de tentative',
                'db_table': 'attempt_answers',
            },
        ),
    ]
