# Generated by Django 6.0.4 on 2026-04-12 14:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_code', models.CharField(editable=False, help_text="Code unique pour vérifier l'authenticité du certificat", max_length=30, unique=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Fichier PDF généré automatiquement', null=True, upload_to='certificates/pdfs/')),
                ('issued_at', models.DateTimeField(auto_now_add=True, help_text='Date de délivrance (immuable)')),
                ('formation_titre_snapshot', models.CharField(editable=False, max_length=200)),
                ('formation_duration_snapshot', models.PositiveIntegerField(default=0, editable=False, help_text='Durée totale de la formation en minutes (au moment de la délivrance)')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.formation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'db_table': 'certificates',
                'ordering': ['-issued_at'],
                'unique_together': {('user', 'formation')},
            },
        ),
    ]
